// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: raft_inspector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	State             string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Term              uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	CommitIndex       uint64                 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex      uint64                 `protobuf:"varint,6,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	LastSnapshotIndex uint64                 `protobuf:"varint,7,opt,name=last_snapshot_index,json=lastSnapshotIndex,proto3" json:"last_snapshot_index,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_raft_inspector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_raft_inspector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_raft_inspector_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NodeInfo) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *NodeInfo) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *NodeInfo) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *NodeInfo) GetLastSnapshotIndex() uint64 {
	if x != nil {
		return x.LastSnapshotIndex
	}
	return 0
}

type ClusterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodesId       []string               `protobuf:"bytes,1,rep,name=nodes_id,json=nodesId,proto3" json:"nodes_id,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Term          uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterInfo) Reset() {
	*x = ClusterInfo{}
	mi := &file_raft_inspector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterInfo) ProtoMessage() {}

func (x *ClusterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_raft_inspector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterInfo.ProtoReflect.Descriptor instead.
func (*ClusterInfo) Descriptor() ([]byte, []int) {
	return file_raft_inspector_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterInfo) GetNodesId() []string {
	if x != nil {
		return x.NodesId
	}
	return nil
}

func (x *ClusterInfo) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *ClusterInfo) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

var File_raft_inspector_proto protoreflect.FileDescriptor

const file_raft_inspector_proto_rawDesc = "" +
	"\n" +
	"\x14raft_inspector.proto\x12\rraftinspector\x1a\x1bgoogle/protobuf/empty.proto\"\xd6\x01\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\x06 \x01(\x04R\fappliedIndex\x12.\n" +
	"\x13last_snapshot_index\x18\a \x01(\x04R\x11lastSnapshotIndex\"Y\n" +
	"\vClusterInfo\x12\x19\n" +
	"\bnodes_id\x18\x01 \x03(\tR\anodesId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term2\x95\x01\n" +
	"\rRaftInspector\x12>\n" +
	"\vGetNodeInfo\x12\x16.google.protobuf.Empty\x1a\x17.raftinspector.NodeInfo\x12D\n" +
	"\x0eGetClusterInfo\x12\x16.google.protobuf.Empty\x1a\x1a.raftinspector.ClusterInfoB0Z.github.com/deamondev/raftinspector/proto;protob\x06proto3"

var (
	file_raft_inspector_proto_rawDescOnce sync.Once
	file_raft_inspector_proto_rawDescData []byte
)

func file_raft_inspector_proto_rawDescGZIP() []byte {
	file_raft_inspector_proto_rawDescOnce.Do(func() {
		file_raft_inspector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_inspector_proto_rawDesc), len(file_raft_inspector_proto_rawDesc)))
	})
	return file_raft_inspector_proto_rawDescData
}

var file_raft_inspector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_raft_inspector_proto_goTypes = []any{
	(*NodeInfo)(nil),      // 0: raftinspector.NodeInfo
	(*ClusterInfo)(nil),   // 1: raftinspector.ClusterInfo
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_raft_inspector_proto_depIdxs = []int32{
	2, // 0: raftinspector.RaftInspector.GetNodeInfo:input_type -> google.protobuf.Empty
	2, // 1: raftinspector.RaftInspector.GetClusterInfo:input_type -> google.protobuf.Empty
	0, // 2: raftinspector.RaftInspector.GetNodeInfo:output_type -> raftinspector.NodeInfo
	1, // 3: raftinspector.RaftInspector.GetClusterInfo:output_type -> raftinspector.ClusterInfo
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_raft_inspector_proto_init() }
func file_raft_inspector_proto_init() {
	if File_raft_inspector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_inspector_proto_rawDesc), len(file_raft_inspector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_inspector_proto_goTypes,
		DependencyIndexes: file_raft_inspector_proto_depIdxs,
		MessageInfos:      file_raft_inspector_proto_msgTypes,
	}.Build()
	File_raft_inspector_proto = out.File
	file_raft_inspector_proto_goTypes = nil
	file_raft_inspector_proto_depIdxs = nil
}
